function [methodinfo,structs,enuminfo,ThunkLibName]=WalabotProto
%WALABOTPROTO Create structures to define interfaces found in 'WalabotAPI'.

%This function was generated by loadlibrary.m parser version  on Fri Jan  9 18:16:37 2026
%perl options:'WalabotAPI.i -outfile=WalabotProto.m -thunkfile=WalabotAPI_thunk_pcwin64.c -header=WalabotAPI.h'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival,'thunkname', ival);
MfilePath=fileparts(mfilename('fullpath'));
ThunkLibName=fullfile(MfilePath,'WalabotAPI_thunk_pcwin64');
% int Walabot_Initialize ( const char * configFilename ); 
fcns.thunkname{fcnNum}='int32cstringThunk';fcns.name{fcnNum}='Walabot_Initialize'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'cstring'};fcnNum=fcnNum+1;
% int Walabot_ConnectAny (); 
fcns.thunkname{fcnNum}='int32Thunk';fcns.name{fcnNum}='Walabot_ConnectAny'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
% int Walabot_SetArenaR ( double min , double max , double res ); 
fcns.thunkname{fcnNum}='int32doubledoubledoubleThunk';fcns.name{fcnNum}='Walabot_SetArenaR'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'double', 'double', 'double'};fcnNum=fcnNum+1;
% int Walabot_SetArenaPhi ( double min , double max , double res ); 
fcns.thunkname{fcnNum}='int32doubledoubledoubleThunk';fcns.name{fcnNum}='Walabot_SetArenaPhi'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'double', 'double', 'double'};fcnNum=fcnNum+1;
% int Walabot_SetArenaTheta ( double min , double max , double res ); 
fcns.thunkname{fcnNum}='int32doubledoubledoubleThunk';fcns.name{fcnNum}='Walabot_SetArenaTheta'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'double', 'double', 'double'};fcnNum=fcnNum+1;
% int Walabot_SetDynamicImageFilter ( int type ); 
fcns.thunkname{fcnNum}='int32int32Thunk';fcns.name{fcnNum}='Walabot_SetDynamicImageFilter'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'int32'};fcnNum=fcnNum+1;
% int Walabot_Start (); 
fcns.thunkname{fcnNum}='int32Thunk';fcns.name{fcnNum}='Walabot_Start'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
% int Walabot_StartCalibration (); 
fcns.thunkname{fcnNum}='int32Thunk';fcns.name{fcnNum}='Walabot_StartCalibration'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
% int Walabot_Stop (); 
fcns.thunkname{fcnNum}='int32Thunk';fcns.name{fcnNum}='Walabot_Stop'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
% int Walabot_Disconnect (); 
fcns.thunkname{fcnNum}='int32Thunk';fcns.name{fcnNum}='Walabot_Disconnect'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
% int Walabot_Clean (); 
fcns.thunkname{fcnNum}='int32Thunk';fcns.name{fcnNum}='Walabot_Clean'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
methodinfo=fcns;